p1:
	gcc -o p1.to p1.c -Wall

p2:
	gcc -o p2.to p2.c -Wall

p3:
	gcc -o p3.to p3.c -Wall

p4:
	gcc -o p4.to p4.c -Wall

e1: 
	gcc -o e1.to e1.c -Wall

e2:
	gcc -o e2.to e2.c -Wall

e5:
	gcc -o e5.to e5.c -Wall

e7:
	gcc -o e7.to e7.c -Wall
