p1:
	gcc -o p1 p1.c -Wall

p2:
	gcc -o p2 p2.c -Wall

p3:
	gcc -o p3 p3.c -Wall

p4: p4.c
	gcc -o p4 p4.c -Wall

e1: e1.c
	gcc -o e1 e1.c -Wall

e2: e2.c
	gcc -o e2 e2.c -Wall

e5: e5.c
	gcc -o e5 e5.c -Wall

e7: e7.c
	gcc -o e7 e7.c -Wall
